"""
SKYNET Bot — Full End-to-End Integration Test

This IS the end-to-end proof that the whole system works.

Journey: hi → Start a Project → name → type → requirements →
         Generate Plan → ✅ Approve → Start Coding → Skip GitHub →
         2 milestones executed → 🎉 complete → ▶️ Run Project → output shown

What is REAL in this test
─────────────────────────
  ✅  SQLite DB (in-memory via init_db(":memory:"))
  ✅  All handler logic and state machine transitions
  ✅  ensure_user / create_project / create_task / update_task_status
  ✅  Keyboard builders, slug derivation, loop coordination
  ✅  Project files written to a real temp directory on disk
  ✅  The project script is actually executed with Python and its
      output is verified

What is stubbed (genuinely unreachable in CI)
─────────────────────────────────────────────
  ⬜  Telegram sends (reply_text / send_message) — can't call live API
  ⬜  AI router .chat() — avoid real paid API calls; plan is deterministic
  ⬜  CLAW WebSocket transport — replaced by a local side-effect that
      writes the same files the real agent would produce and then runs
      them via subprocess
"""
from __future__ import annotations

import asyncio
import os
import subprocess
import sys
import tempfile
import textwrap
import pytest
from unittest.mock import AsyncMock, MagicMock, patch

from telegram.ext import ConversationHandler

from helpers import make_callback_update, make_message_update, make_context

from bot.handlers.greeting import greeting_handler
from bot.handlers.project import (
    ask_project_name, approve_plan,
    receive_project_name, receive_project_type,
    requirements_done_handler,
    _NAME_KEY, _TYPE_KEY, _PLAN_KEY, _REQS_HISTORY,
    AWAITING_PROJECT_NAME, AWAITING_PROJECT_TYPE,
    GATHERING_REQUIREMENTS, REVIEWING_PLAN,
)
from bot.handlers.coding import (
    start_coding_handler, coding_github_choice_handler,
    run_project_handler,
    _MS_EVENT_KEY, _MS_DECISION_KEY, _ACTIVE_LOOP_KEY,
    _CODING_PID_KEY,
)
from bot.keyboards import (
    CB_START_PROJECT, CB_PLAN_APPROVE, CB_REQUIREMENTS_DONE,
    CB_START_CODING, CB_CODING_GITHUB_SKIP, CB_RUN_PROJECT,
)
from bot.state import KEY_DB, KEY_ROUTER
from db.schema import init_db
from db.store  import get_project, list_tasks


# ─────────────────────────────────────────────────────────────────────────────

@pytest.mark.asyncio
async def test_full_flow_hi_to_project_deliverables(tmp_path):
    """
    Walks every handler in sequence.  Project files land on disk; the final
    step actually runs the script and checks its output.
    """

    # ── Setup ─────────────────────────────────────────────────────────────────
    db      = await init_db(":memory:")
    USER_ID = 55
    CHAT_ID = 200
    SLUG    = "integrationproject"

    MILESTONES = [
        "Set up project structure",
        "Implement main logic",
    ]
    FAKE_PLAN = (
        "**IntegrationProject — Project Plan**\n"
        "**Overview:** A test CLI app.\n"
        "**Milestones:**\n"
        "  1. Set up project structure\n"
        "  2. Implement main logic"
    )

    # Use tmp_path (pytest fixture) as the project base dir so files are real
    project_dir  = tmp_path / SLUG
    project_file = project_dir / f"{SLUG}.py"

    # AI router stub
    fake_router       = MagicMock()
    fake_router.chat  = AsyncMock(return_value=MagicMock(text=FAKE_PLAN))

    # Shared bot_data (app + all contexts share the same dict)
    bot_data = {KEY_DB: db, KEY_ROUTER: fake_router}

    app           = MagicMock()
    app.bot_data  = bot_data
    sent_by_loop: list[str] = []

    async def _loop_send(cid, text, **kw):
        sent_by_loop.append(text)

    app.bot.send_message = AsyncMock(side_effect=_loop_send)

    def make_ctx(extra_user_data=None):
        c = make_context(
            user_data={} if extra_user_data is None else extra_user_data,
            bot_data=bot_data,
        )
        c.application = app
        return c

    user_data: dict = {}

    # ─── CLAW worker stub ─────────────────────────────────────────────────────
    # run_coding_agent  → creates a real Python file inside tmp_path
    # list_directory    → returns listing used to detect project entry point
    # exec_command      → actually runs that Python file with subprocess

    async def fake_send_action(action, params, **kw):
        if action == "run_coding_agent":
            wd = params["working_dir"]
            os.makedirs(wd, exist_ok=True)
            slug = os.path.basename(wd)
            script = os.path.join(wd, f"{slug}.py")
            with open(script, "w", encoding="utf-8") as f:
                f.write(textwrap.dedent(f"""\
                    # Generated by SKYNET integration test
                    def main():
                        print("Hello from {slug}!")
                        return 0

                    if __name__ == "__main__":
                        raise SystemExit(main())
                """))
            return {
                "stdout": f"Wrote 1 file(s): {slug}.py",
                "exit_code": 0,
                "files_written": [f"{slug}.py"],
            }

        if action == "list_directory":
            wd = params["directory"]
            if not os.path.isdir(wd):
                return {"stdout": "", "stderr": "directory not found", "returncode": 1}
            lines = []
            for name in sorted(os.listdir(wd)):
                path = os.path.join(wd, name)
                if os.path.isdir(path):
                    lines.append(f"[DIR] {name}/")
                else:
                    lines.append(f"{name}  ({os.path.getsize(path)} bytes)")
            return {
                "stdout": "\n".join(lines),
                "stderr": "",
                "returncode": 0,
            }

        if action == "exec_command":
            cmd = params["command"]          # e.g. "python integrationproject.py"
            wd  = params["working_dir"]

            proc = subprocess.run(
                [sys.executable] + cmd.split()[1:],   # replace "python" with current interpreter
                cwd=wd,
                capture_output=True,
                text=True,
            )
            return {
                "stdout":    proc.stdout,
                "stderr":    proc.stderr,
                "exit_code": proc.returncode,
            }

        return {"stdout": "", "exit_code": 0}

    # ─────────────────────────────────────────────────────────────────────────
    # STEP 1 — "hi" → main menu contains Start a Project
    # ─────────────────────────────────────────────────────────────────────────
    upd = make_message_update("hi", user_id=USER_ID)
    await greeting_handler(upd, make_ctx())

    markup   = upd.message.reply_text.call_args.kwargs["reply_markup"]
    all_data = [btn.callback_data for row in markup.inline_keyboard for btn in row]
    assert CB_START_PROJECT in all_data, "Greeting must contain Start a Project button"

    # ─────────────────────────────────────────────────────────────────────────
    # STEP 2 — Start a Project → asks for name
    # ─────────────────────────────────────────────────────────────────────────
    upd   = make_callback_update(CB_START_PROJECT, user_id=USER_ID)
    state = await ask_project_name(upd, make_ctx())
    assert state == AWAITING_PROJECT_NAME

    # ─────────────────────────────────────────────────────────────────────────
    # STEP 3 — Type project name
    # ─────────────────────────────────────────────────────────────────────────
    upd = make_message_update("IntegrationProject", user_id=USER_ID)
    c   = make_ctx(extra_user_data=user_data)
    state = await receive_project_name(upd, c)
    user_data.update(c.user_data)

    assert state == AWAITING_PROJECT_TYPE
    assert user_data[_NAME_KEY] == "IntegrationProject"

    # ─────────────────────────────────────────────────────────────────────────
    # STEP 4 — Select Python App
    # ─────────────────────────────────────────────────────────────────────────
    upd = make_callback_update("type:python_app", user_id=USER_ID)
    c   = make_ctx(extra_user_data=user_data)
    state = await receive_project_type(upd, c)
    user_data.update(c.user_data)

    assert state == GATHERING_REQUIREMENTS
    assert user_data[_TYPE_KEY] == "Python App"

    # ─────────────────────────────────────────────────────────────────────────
    # STEP 5 — Done — Generate Plan
    # ─────────────────────────────────────────────────────────────────────────
    upd = make_callback_update(CB_REQUIREMENTS_DONE, user_id=USER_ID)
    c   = make_ctx(extra_user_data=user_data)
    state = await requirements_done_handler(upd, c)
    user_data.update(c.user_data)

    assert state == REVIEWING_PLAN
    assert user_data[_PLAN_KEY] == FAKE_PLAN

    # ─────────────────────────────────────────────────────────────────────────
    # STEP 6 — ✅ Approve → project row in real DB
    # ─────────────────────────────────────────────────────────────────────────
    upd    = make_callback_update(CB_PLAN_APPROVE, user_id=USER_ID)
    c      = make_ctx(extra_user_data=user_data)
    result = await approve_plan(upd, c)
    user_data.update(c.user_data)

    assert result == ConversationHandler.END

    project_id = user_data.get("last_project_id")
    assert project_id, "approve_plan must set last_project_id"

    row = await get_project(db, project_id)
    assert row is not None,                        "Project row missing from DB"
    assert row["name"]         == "IntegrationProject"
    assert row["project_type"] == "Python App"
    assert row["description"]  == FAKE_PLAN
    assert row["status"]       == "approved"

    # ─────────────────────────────────────────────────────────────────────────
    # STEP 7 — Start Coding
    # ─────────────────────────────────────────────────────────────────────────
    upd = make_callback_update(CB_START_CODING, user_id=USER_ID, chat_id=CHAT_ID)
    c   = make_ctx(extra_user_data={"last_project_id": project_id})
    await start_coding_handler(upd, c)
    assert c.user_data.get(_CODING_PID_KEY) == project_id

    # ─────────────────────────────────────────────────────────────────────────
    # STEP 8 — Skip GitHub → coding loop starts; milestones auto-approved
    # ─────────────────────────────────────────────────────────────────────────
    loop_key  = _ACTIVE_LOOP_KEY.format(uid=USER_ID)
    event_key = _MS_EVENT_KEY.format(uid=USER_ID)
    dec_key   = _MS_DECISION_KEY.format(uid=USER_ID)

    async def auto_approve_all():
        for _ in range(len(MILESTONES)):
            for _ in range(500):
                if event_key in bot_data:
                    break
                await asyncio.sleep(0.01)
            else:
                raise AssertionError("Milestone event never appeared in bot_data")
            bot_data[dec_key] = "approve"
            bot_data[event_key].set()
            # wait for loop to consume the event
            for _ in range(500):
                if event_key not in bot_data:
                    break
                await asyncio.sleep(0.01)

    approve_task = asyncio.create_task(auto_approve_all())

    upd = make_callback_update(CB_CODING_GITHUB_SKIP, user_id=USER_ID, chat_id=CHAT_ID)
    c   = make_ctx(extra_user_data={_CODING_PID_KEY: project_id})

    with (
        patch("bot.handlers.coding._extract_milestones",
              new=AsyncMock(return_value=MILESTONES)),
        patch("bot.handlers.coding.is_worker_available", return_value=True),
        patch("bot.handlers.coding.send_action",
              new=AsyncMock(side_effect=fake_send_action)),
        patch("bot.handlers.coding.cfg") as mock_cfg,
    ):
        mock_cfg.WORKER_PROJECTS_DIR = str(tmp_path)

        await coding_github_choice_handler(upd, c)

        loop_task = bot_data.get(loop_key)
        assert loop_task is not None, "Loop task not created"
        await asyncio.wait_for(loop_task, timeout=15)

    await approve_task

    # ─────────────────────────────────────────────────────────────────────────
    # STEP 9 — Verify tasks in real DB, all done
    # ─────────────────────────────────────────────────────────────────────────
    tasks = await list_tasks(db, project_id=project_id)
    assert len(tasks) == len(MILESTONES), (
        f"Expected {len(MILESTONES)} task rows; got {len(tasks)}"
    )
    for t in tasks:
        assert t["status"] == "done", f"Task {t['title']!r} not done: {t['status']}"

    # ─────────────────────────────────────────────────────────────────────────
    # STEP 10 — Verify project file was written to disk
    # ─────────────────────────────────────────────────────────────────────────
    assert project_dir.is_dir(), (
        f"Project directory not created on disk: {project_dir}"
    )
    assert project_file.is_file(), (
        f"Project script not created on disk: {project_file}"
    )
    src = project_file.read_text(encoding="utf-8")
    assert "def main" in src or "print" in src, (
        f"Project file looks empty or wrong:\n{src}"
    )

    # Completion message has 🎉 and 📁
    done_msgs = [m for m in sent_by_loop if "🎉" in m]
    assert done_msgs, f"No completion message; messages: {sent_by_loop}"
    assert "📁" in done_msgs[0]
    assert bot_data.get(f"run_project_{USER_ID}") == project_id
    assert bot_data.get(f"run_files_{USER_ID}"), "run_files must be set after coding loop"

    # ─────────────────────────────────────────────────────────────────────────
    # STEP 11 — ▶️ Run Project → actually executes the file, checks output
    # ─────────────────────────────────────────────────────────────────────────
    upd = make_callback_update(CB_RUN_PROJECT, user_id=USER_ID, chat_id=CHAT_ID)
    c   = make_context(bot_data=dict(bot_data))

    with (
        patch("bot.handlers.coding.is_worker_available", return_value=True),
        patch("bot.handlers.coding.send_action",
              new=AsyncMock(side_effect=fake_send_action)) as mock_run,
        patch("bot.handlers.coding.cfg") as mock_cfg2,
    ):
        mock_cfg2.WORKER_PROJECTS_DIR = str(tmp_path)
        await run_project_handler(upd, c)

    # exec_command dispatched with correct script + working_dir
    mock_run.assert_awaited()
    exec_calls = [
        ca for ca in mock_run.call_args_list
        if ca.args[0] == "exec_command" and "python" in ca.args[1].get("command", "")
    ]
    assert exec_calls, "exec_command must be dispatched to run the project"
    params = exec_calls[0].args[1]
    assert f"{SLUG}.py" in params["command"],   f"Wrong command: {params['command']}"
    assert SLUG in params["working_dir"].lower(), f"Wrong working_dir: {params['working_dir']}"

    # The reply to the user contains the real stdout from the Python script
    all_replies = " ".join(
        c.args[0] if c.args else ""
        for c in upd.callback_query.message.reply_text.call_args_list
    )
    assert f"Hello from {SLUG}" in all_replies, (
        f"Expected script stdout in chat; got: {all_replies!r}"
    )
    assert "exit 0" in all_replies or "✅" in all_replies

    # ── Cleanup ───────────────────────────────────────────────────────────────
    await db.close()
