"""
SKYNET Bot — Coding Orchestration

Handles the full coding loop after a project is saved:
  1. User taps "Start Coding"
  2. Bot asks about GitHub repo / project folder setup (buttons)
  3. User confirms → background asyncio.Task starts
  4. Loop: LLM breaks plan into milestones → user approves each → CLAW worker executes
  5. Progress notifications after each milestone
  6. /status command shows live dashboard

Key design: _coding_loop runs as a background asyncio.Task.
Milestone approvals are signalled via asyncio.Event stored in bot_data.
"""
from __future__ import annotations

import asyncio
import html as html_mod
import json
import logging
import re

import config as cfg
from telegram import Update
from telegram.ext import ContextTypes

from bot.keyboards import (
    CB_CODING_RETRY_PREFIX,
    CB_CODING_GITHUB_SKIP,
    CB_CODING_GITHUB_YES,
    coding_github_setup,
    main_menu,
    milestone_review,
    retry_coding,
    run_project,
)
from bot.state import KEY_DB, KEY_ROUTER
from db.store import (
    create_task,
    ensure_user,
    get_project,
    list_projects,
    list_tasks,
    update_task_status,
)
from gateway import is_worker_available, send_action

logger = logging.getLogger("skynet.bot.coding")

# Run manifest generated by coding agent for deterministic "Run Project".
_RUN_MANIFEST_FILENAME = "skynet_run.json"
_ALLOWED_RUN_INTERPRETERS = ("python", "python3", "node")

# bot_data keys for inter-handler signalling
_MS_EVENT_KEY    = "ms_event_{uid}"
_MS_DECISION_KEY = "ms_decision_{uid}"
_ACTIVE_LOOP_KEY = "coding_loop_{uid}"   # stores the asyncio.Task
_GITHUB_PREF_KEY = "coding_github_pref_{uid}_{pid}"

# User_data key set by project handler after save
_PROJECT_ID_KEY = "last_project_id"
_CODING_PID_KEY = "coding_project_id"


# ── Entry: Start Coding ───────────────────────────────────────────────────────

async def start_coding_handler(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
) -> None:
    """User tapped 🚀 Start Coding — ask GitHub/folder setup preference."""
    await update.callback_query.answer()

    project_id = context.user_data.get(_PROJECT_ID_KEY)
    if not project_id:
        await update.callback_query.message.reply_text(
            "No active project found. Start a project first.",
            reply_markup=main_menu(),
        )
        return

    context.user_data[_CODING_PID_KEY] = project_id

    await update.callback_query.message.reply_text(
        "Should I set up a GitHub repo and project folder on your laptop?",
        reply_markup=coding_github_setup(),
    )


async def _start_coding_loop(
    *,
    context: ContextTypes.DEFAULT_TYPE,
    message,
    user_id: int,
    chat_id: int,
    project: dict,
    do_github: bool,
) -> bool:
    """Start a coding session task, guarding against duplicate active loops."""
    loop_key = _ACTIVE_LOOP_KEY.format(uid=user_id)
    existing = context.bot_data.get(loop_key)
    if existing and not existing.done():
        await message.reply_text("A coding session is already running for you!")
        return False

    context.bot_data.pop(f"run_project_{user_id}", None)
    slug = _slugify(project["name"])
    working_dir = f"{cfg.WORKER_PROJECTS_DIR}/{slug}"

    await message.reply_text(
        "Starting coding session…\n"
        f"📁 Project folder: <code>{working_dir}</code>\n\n"
        "I'll send you each milestone for approval before executing. "
        "Use /status anytime to check progress.",
        parse_mode="HTML",
    )

    task = asyncio.create_task(
        _coding_loop(context.application, chat_id, user_id, project, do_github)
    )
    context.bot_data[loop_key] = task
    return True


async def coding_github_choice_handler(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
) -> None:
    """User chose GitHub setup option — spin up the background coding loop."""
    await update.callback_query.answer()

    cb_data    = update.callback_query.data or ""
    project_id = context.user_data.pop(_CODING_PID_KEY, None)
    user_id    = update.effective_user.id
    chat_id    = update.effective_chat.id

    if not project_id:
        await update.callback_query.message.reply_text("Session expired — start over.")
        return

    db = context.bot_data.get(KEY_DB)
    project = await get_project(db, project_id)
    if not project:
        await update.callback_query.message.reply_text("Project not found in database.")
        return

    do_github = (cb_data == CB_CODING_GITHUB_YES)

    context.bot_data[_GITHUB_PREF_KEY.format(uid=user_id, pid=project_id)] = do_github

    await _start_coding_loop(
        context=context,
        message=update.callback_query.message,
        user_id=user_id,
        chat_id=chat_id,
        project=project,
        do_github=do_github,
    )


# ── Milestone approval callbacks ─────────────────────────────────────────────

async def retry_coding_handler(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
) -> None:
    """Retry coding for a saved project, reusing the previous GitHub preference when known."""
    await update.callback_query.answer()

    cb_data = update.callback_query.data or ""
    project_id = cb_data.removeprefix(CB_CODING_RETRY_PREFIX).strip()
    if not project_id:
        await update.callback_query.message.reply_text(
            "Invalid retry request.",
            reply_markup=main_menu(),
        )
        return

    db = context.bot_data.get(KEY_DB)
    tg_user = update.effective_user
    user = await ensure_user(
        db,
        telegram_user_id=tg_user.id,
        username=tg_user.username or "",
        first_name=tg_user.first_name or "",
        last_name=tg_user.last_name or "",
    )

    project = await get_project(db, project_id)
    if not project or int(project.get("user_id", -1)) != int(user["id"]):
        await update.callback_query.message.reply_text(
            "This retry link is invalid or you no longer have access to this project.",
            reply_markup=main_menu(),
        )
        return

    context.user_data[_PROJECT_ID_KEY] = project_id
    pref_key = _GITHUB_PREF_KEY.format(uid=tg_user.id, pid=project_id)
    remembered_pref = context.bot_data.get(pref_key)
    if isinstance(remembered_pref, bool):
        mode_label = "GitHub repo + folder setup" if remembered_pref else "folder-only setup"
        await update.callback_query.message.reply_text(
            f"Retrying with your previous preference: {mode_label}."
        )
        await _start_coding_loop(
            context=context,
            message=update.callback_query.message,
            user_id=tg_user.id,
            chat_id=update.effective_chat.id,
            project=project,
            do_github=remembered_pref,
        )
        return

    context.user_data[_CODING_PID_KEY] = project_id
    await update.callback_query.message.reply_text(
        "Should I set up a GitHub repo and project folder on your laptop?",
        reply_markup=coding_github_setup(),
    )

async def approve_milestone_handler(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
) -> None:
    """User tapped ✅ Run It — signal the coding loop to proceed."""
    await update.callback_query.answer("Running…")
    user_id  = update.effective_user.id
    event_key = _MS_EVENT_KEY.format(uid=user_id)
    event: asyncio.Event | None = context.bot_data.get(event_key)
    if event:
        context.bot_data[_MS_DECISION_KEY.format(uid=user_id)] = "approve"
        event.set()
    else:
        await update.callback_query.message.reply_text(
            "No active milestone waiting for approval."
        )


async def skip_milestone_handler(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
) -> None:
    """User tapped ⏭ Skip — signal the coding loop to skip this milestone."""
    await update.callback_query.answer("Skipping…")
    user_id   = update.effective_user.id
    event_key = _MS_EVENT_KEY.format(uid=user_id)
    event: asyncio.Event | None = context.bot_data.get(event_key)
    if event:
        context.bot_data[_MS_DECISION_KEY.format(uid=user_id)] = "skip"
        event.set()


async def stop_milestone_handler(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
) -> None:
    """User tapped 🛑 Stop Session — signal the coding loop to abort."""
    await update.callback_query.answer("Stopping…")
    user_id   = update.effective_user.id
    event_key = _MS_EVENT_KEY.format(uid=user_id)
    event: asyncio.Event | None = context.bot_data.get(event_key)
    if event:
        context.bot_data[_MS_DECISION_KEY.format(uid=user_id)] = "stop"
        event.set()
    else:
        await update.callback_query.message.reply_text(
            "No active coding session to stop."
        )


# ── Dashboard ─────────────────────────────────────────────────────────────────

async def dashboard_handler(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
) -> None:
    """/status — show the latest project's task progress."""
    from telegram import InlineKeyboardButton, InlineKeyboardMarkup

    db      = context.bot_data.get(KEY_DB)
    tg_user = update.effective_user

    user = await ensure_user(
        db,
        telegram_user_id=tg_user.id,
        username=tg_user.username    or "",
        first_name=tg_user.first_name or "",
        last_name=tg_user.last_name   or "",
    )
    projects = await list_projects(db, user_id=user["id"])
    if not projects:
        await update.message.reply_text(
            "No projects yet. Tap 🚀 Start a Project to begin.",
            reply_markup=main_menu(),
        )
        return

    project = projects[0]  # most recent
    tasks   = await list_tasks(db, project_id=project["id"])

    STATUS_EMOJI = {
        "pending": "⏳",
        "running": "⚙️",
        "done":    "✅",
        "failed":  "❌",
    }

    if tasks:
        task_lines = "\n".join(
            f"{STATUS_EMOJI.get(t['status'], '❓')} {t['title']}"
            for t in tasks
        )
    else:
        task_lines = "No tasks yet — coding hasn't started."

    loop_key   = _ACTIVE_LOOP_KEY.format(uid=tg_user.id)
    is_running = (
        loop_key in context.bot_data
        and context.bot_data[loop_key]
        and not context.bot_data[loop_key].done()
    )
    status_note = " | 🔄 Coding in progress" if is_running else ""

    slug        = _slugify(project["name"])
    working_dir = f"{cfg.WORKER_PROJECTS_DIR}/{slug}"

    text = (
        f"<b>📊 {project['name']}</b> — {project['project_type']}\n"
        f"📁 <code>{working_dir}</code>\n"
        f"Status: {project['status']}{status_note}\n\n"
        f"{task_lines}"
    )

    # Show Run Project button if coding is done and a project_id is stored.
    run_pid = context.bot_data.get(f"run_project_{tg_user.id}")
    if run_pid and not is_running:
        keyboard = run_project()
    else:
        keyboard = InlineKeyboardMarkup([
            [InlineKeyboardButton("🏠 Main Menu", callback_data="nav:main_menu")],
        ])
    await update.message.reply_text(text, parse_mode="HTML", reply_markup=keyboard)


# ── Background coding loop ────────────────────────────────────────────────────

async def _coding_loop(
    app,
    chat_id: int,
    user_id: int,
    project: dict,
    do_github: bool,
) -> None:
    """
    Background task: orchestrate milestone-by-milestone project execution.

    1. (Optional) Set up GitHub repo + project folder on CLAW worker.
    2. Extract milestones from the stored plan via LLM.
    3. For each milestone:
       a. Send to user with ✅ Run It / ⏭ Skip buttons.
       b. Wait up to 1 h for user decision.
       c. If approved: dispatch run_coding_agent to CLAW worker.
       d. Notify user of result.
    4. Send completion message.
    """
    db     = app.bot_data.get(KEY_DB)
    router = app.bot_data.get(KEY_ROUTER)
    slug   = _slugify(project["name"])
    working_dir = f"{cfg.WORKER_PROJECTS_DIR}/{slug}"

    try:
        # ── Always create the project folder on the worker ────────────────────
        if is_worker_available():
            try:
                await send_action(
                    "create_directory",
                    {"directory": working_dir},
                    confirmed=True,
                )
            except Exception:
                pass  # Directory may already exist — not fatal.
        else:
            await app.bot.send_message(
                chat_id, "⚠️ Worker not connected — cannot create project folder."
            )
            return

        # ── Optional GitHub setup ──────────────────────────────────────────────
        if do_github:
            await app.bot.send_message(chat_id, "🔧 Setting up GitHub repo and project folder…")
            try:
                # Step 1: git init.
                init_result = await send_action(
                    "git_init",
                    {"working_dir": working_dir},
                    confirmed=True,
                )
                if init_result.get("status") == "error":
                    raise RuntimeError(init_result.get("error", "git init failed"))
                _init_inner = init_result.get("result", {})
                if _init_inner.get("returncode", 0) != 0:
                    raise RuntimeError(_init_inner.get("stderr") or _init_inner.get("stdout") or "git init failed")

                # Step 2: write a README so the initial push has a commit.
                readme_content = (
                    f"# {project['name']}\n\n"
                    f"{project.get('description') or project.get('project_type', '')}\n\n"
                    "_Created by SKYNET_\n"
                )
                readme_path = f"{working_dir}/README.md"
                fw_result = await send_action(
                    "file_write",
                    {"file": readme_path, "content": readme_content},  # key is "file" not "path"
                    confirmed=True,
                )
                _fw_inner = fw_result.get("result", fw_result)
                if _fw_inner.get("returncode", 0) != 0:
                    raise RuntimeError(
                        _fw_inner.get("stderr") or _fw_inner.get("stdout") or "file_write failed"
                    )

                # Step 3: stage + commit README.
                await send_action("git_add_all", {"working_dir": working_dir}, confirmed=True)
                commit_result = await send_action(
                    "git_commit",
                    {"working_dir": working_dir, "message": "Initial commit"},
                    confirmed=True,
                )
                _commit_inner = commit_result.get("result", {})
                if _commit_inner.get("returncode", 0) != 0:
                    raise RuntimeError(
                        _commit_inner.get("stderr") or _commit_inner.get("stdout") or "git commit failed"
                    )

                # Step 4: create GitHub repo and push the initial commit.
                gh_result = await send_action(
                    "gh_create_repo",
                    {
                        "working_dir": working_dir,
                        "repo_name":   slug,
                        "description": f"Created by SKYNET — {project['project_type']}",
                        "private":     True,
                    },
                    timeout=120,
                    confirmed=True,
                )
                if gh_result.get("status") == "error":
                    raise RuntimeError(gh_result.get("error", "Unknown error"))
                _gh_inner = gh_result.get("result", {})
                if _gh_inner.get("returncode", 0) != 0:
                    raise RuntimeError(_gh_inner.get("stderr") or _gh_inner.get("stdout") or "gh_create_repo failed")
                await app.bot.send_message(chat_id, "✅ GitHub repo created and pushed.")
            except Exception as exc:
                await app.bot.send_message(
                    chat_id, f"⚠️ GitHub setup failed: {exc}\nContinuing anyway…"
                )

        # ── Extract milestones from plan ──────────────────────────────────────
        await app.bot.send_message(chat_id, "📋 Breaking the plan into milestones…")
        milestones = await _extract_milestones(router, project)
        total = len(milestones)

        if not milestones:
            await app.bot.send_message(
                chat_id,
                "Could not extract milestones from the plan. "
                "Please refine your plan and try again.",
                reply_markup=main_menu(),
            )
            return

        await app.bot.send_message(
            chat_id, f"Found <b>{total} milestone(s)</b>. Let's go!", parse_mode="HTML"
        )

        successful_milestones = 0
        failed_milestones = 0
        skipped_milestones = 0
        all_written_files: list[str] = []

        # ── Milestone loop ────────────────────────────────────────────────────
        for i, milestone_text in enumerate(milestones, 1):
            # Show milestone to user.
            await app.bot.send_message(
                chat_id,
                f"<b>Milestone {i}/{total}</b>\n\n{milestone_text}",
                parse_mode="HTML",
                reply_markup=milestone_review(),
            )

            # Wait for user decision (up to 1 hour).
            event = asyncio.Event()
            event_key    = _MS_EVENT_KEY.format(uid=user_id)
            decision_key = _MS_DECISION_KEY.format(uid=user_id)
            app.bot_data[event_key] = event
            app.bot_data.pop(decision_key, None)

            try:
                await asyncio.wait_for(event.wait(), timeout=3600)
            except asyncio.TimeoutError:
                await app.bot.send_message(
                    chat_id, f"⏰ Milestone {i} timed out — skipping."
                )
                app.bot_data.pop(event_key, None)
                skipped_milestones += 1
                continue

            app.bot_data.pop(event_key, None)
            decision = app.bot_data.pop(decision_key, "skip")

            if decision == "stop":
                await app.bot.send_message(
                    chat_id,
                    f"🛑 Session stopped at milestone {i}/{total}.\n"
                    "Use /status to review completed milestones.",
                )
                return

            if decision == "skip":
                await app.bot.send_message(chat_id, f"⏭ Milestone {i} skipped.")
                skipped_milestones += 1
                continue

            # Create DB task record.
            short_title = milestone_text[:80].split("\n")[0]
            task_rec = await create_task(
                db,
                project_id=project["id"],
                title=f"Milestone {i}: {short_title}",
                description=milestone_text,
            )
            await update_task_status(db, task_rec["id"], status="running")
            await app.bot.send_message(chat_id, f"⚙️ Executing milestone {i}…")

            # Dispatch to CLAW worker.
            if not is_worker_available():
                await app.bot.send_message(
                    chat_id, "⚠️ Worker disconnected — cannot execute. Skipping."
                )
                await update_task_status(
                    db, task_rec["id"],
                    status="failed", error_message="Agent not connected",
                )
                failed_milestones += 1
                continue

            prompt = (
                f"Project: {project['name']} ({project['project_type']})\n"
                f"Working directory: {working_dir}\n\n"
                f"Task:\n{milestone_text}\n\n"
                "Implement this task completely. Write all necessary files, "
                "then run tests if applicable.\n\n"
                f"When deciding how the project should be launched, create or update "
                f"{_RUN_MANIFEST_FILENAME} in the project root using this JSON schema:\n"
                '{"interpreter":"python|python3|node","entrypoint":"relative/path","args":["optional","tokens"]}\n'
                "Use only relative entrypoint paths and argument tokens without spaces."
            )
            try:
                result = await send_action(
                    "run_coding_agent",
                    {
                        "prompt":      prompt,
                        "working_dir": working_dir,
                    },
                    timeout=1800,
                    confirmed=True,
                )
                # Worker wraps result: {"status": "success"/"error", "result": {...}}
                if result.get("status") == "error":
                    raise RuntimeError(result.get("error", "run_coding_agent failed"))

                inner = result.get("result", result)
                return_code = inner.get("returncode", inner.get("exit_code", 0))
                if return_code != 0:
                    detail = (
                        inner.get("stderr")
                        or inner.get("stdout")
                        or f"run_coding_agent exited with code {return_code}"
                    )
                    raise RuntimeError(str(detail))

                summary = (inner.get("stdout") or inner.get("stderr") or "")[:500].strip()

                # Track written files for the run handler.
                written = inner.get("files_written") or []
                if written:
                    all_written_files.extend(written)
                else:
                    # Fallback: parse "Wrote N file(s): a.py, b.py" from stdout
                    m = re.search(r"Wrote \d+ file\(s\): (.+)", summary)
                    if m:
                        all_written_files.extend(
                            f.strip() for f in m.group(1).split(",") if f.strip()
                        )

                await update_task_status(
                    db, task_rec["id"], status="done", result_summary=summary
                )
                successful_milestones += 1
                notice = f"✅ Milestone {i} complete!"
                if summary:
                    notice += f"\n\n{summary}"
                await app.bot.send_message(chat_id, notice)

            except Exception as exc:
                err = str(exc)[:300]
                await update_task_status(
                    db, task_rec["id"], status="failed", error_message=err
                )
                failed_milestones += 1
                await app.bot.send_message(
                    chat_id, f"❌ Milestone {i} failed:\n<code>{html_mod.escape(str(err))}</code>",
                    parse_mode="HTML",
                )

        # ── Done ──────────────────────────────────────────────────────────────
        milestone_summary = (
            f"complete={successful_milestones}, "
            f"failed={failed_milestones}, "
            f"skipped={skipped_milestones}"
        )
        if successful_milestones > 0:
            app.bot_data[f"run_project_{user_id}"] = project["id"]
            app.bot_data[f"run_files_{user_id}"] = all_written_files
            await app.bot.send_message(
                chat_id,
                f"\U0001F389 <b>{project['name']}</b> coding session complete!\n"
                f"\U0001F4C1 <code>{working_dir}</code>\n"
                f"{milestone_summary}\n\n"
                "Use /status to review milestones or run the project now.",
                parse_mode="HTML",
                reply_markup=run_project(),
            )
        else:
            await app.bot.send_message(
                chat_id,
                f"\u26A0\uFE0F <b>{project['name']}</b> session finished with no successful milestones.\n"
                f"\U0001F4C1 <code>{working_dir}</code>\n"
                f"{milestone_summary}\n\n"
                "Tap Retry Coding to run again with your previous GitHub setup mode, "
                "or use /status to inspect failures first.",
                parse_mode="HTML",
                reply_markup=retry_coding(project["id"]),
            )

    except Exception:
        logger.exception("Coding loop crashed for project %s user %s", project["id"], user_id)
        await app.bot.send_message(
            chat_id,
            "An unexpected error occurred in the coding loop. "
            "Use /status to see what was completed.",
            reply_markup=main_menu(),
        )


# ── Run Project ───────────────────────────────────────────────────────────────

async def run_project_handler(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
) -> None:
    """User tapped ▶️ Run Project — execute the project script on the CLAW worker."""
    await update.callback_query.answer()

    user_id = update.effective_user.id
    db      = context.bot_data.get(KEY_DB)

    # Prefer the project from the last coding session; fallback to most recent.
    pid_key    = f"run_project_{user_id}"
    project_id = context.bot_data.get(pid_key)
    project    = None
    if project_id:
        project = await get_project(db, project_id)

    if not project:
        tg_user  = update.effective_user
        user     = await ensure_user(
            db,
            telegram_user_id=tg_user.id,
            username=tg_user.username    or "",
            first_name=tg_user.first_name or "",
            last_name=tg_user.last_name   or "",
        )
        projects = await list_projects(db, user_id=user["id"])
        project  = projects[0] if projects else None

    if not project:
        await update.callback_query.message.reply_text(
            "No project found to run.", reply_markup=main_menu()
        )
        return

    if not is_worker_available():
        await update.callback_query.message.reply_text(
            "⚠️ Worker not connected — can't run the project right now.",
            reply_markup=run_project(),
        )
        return

    slug        = _slugify(project["name"])
    working_dir = f"{cfg.WORKER_PROJECTS_DIR}/{slug}"
    project_type = str(project.get("project_type", "") or "")

    # --- Detect the actual entry-point script --------------------------------
    # Priority 1: use files stored during the coding loop (no network needed).
    stored_files = context.bot_data.get(f"run_files_{user_id}") or []
    if stored_files:
        resolved = _select_entrypoint(
            files=stored_files, slug=slug, project_type=project_type,
        )
    else:
        resolved = None

    # Priority 2: fall back to listing the directory on the worker.
    if not resolved:
        try:
            list_result = await send_action(
                "list_directory",
                {"directory": working_dir, "recursive": True},
                timeout=20,
                confirmed=True,
            )
            if list_result.get("status") == "error":
                raise RuntimeError(list_result.get("error", "list_directory failed"))

            list_inner = list_result.get("result", list_result)
            list_code = list_inner.get("returncode", list_inner.get("exit_code", 1))
            if list_code != 0:
                detail = list_inner.get("stderr") or list_inner.get("stdout") or "list_directory failed"
                raise RuntimeError(str(detail))

            listing = str(list_inner.get("stdout") or "")
            discovered_files = _extract_file_paths_from_listing(listing, working_dir=working_dir)
            resolved = _select_entrypoint(
                files=discovered_files, slug=slug, project_type=project_type,
            )
        except Exception as exc:
            logger.warning("Could not list project dir %s: %s", working_dir, exc)

    if not resolved:
        await update.callback_query.message.reply_text(
            f"⚠️ No runnable entry point found in <code>{html_mod.escape(working_dir)}</code>.\n"
            "The coding agent may not have finished writing files. "
            "Try running the coding loop again.",
            parse_mode="HTML",
            reply_markup=main_menu(),
        )
        return

    run_cmd, run_target = resolved

    await update.callback_query.message.reply_text(
        f"▶️ Running <code>{html_mod.escape(run_target or '')}</code> on your laptop…",
        parse_mode="HTML",
    )

    try:
        result = await send_action(
            "exec_command",
            {"command": run_cmd, "working_dir": working_dir},
            timeout=60,
            confirmed=True,
        )
        if result.get("status") == "error":
            raise RuntimeError(result.get("error", "exec_command failed"))

        # The gateway wraps the worker's response: {"status": "success", "result": {...}}
        inner     = result.get("result", result)
        stdout    = (inner.get("stdout") or "").strip()
        stderr    = (inner.get("stderr") or "").strip()
        exit_code = inner.get("returncode", inner.get("exit_code", 0))

        output = html_mod.escape((stdout or stderr or "(no output)")[:1000])
        status_line = (
            f"✅ Finished (exit {exit_code})"
            if exit_code == 0
            else f"❌ Exited with code {exit_code}"
        )
        await update.callback_query.message.reply_text(
            f"<pre>{output}</pre>\n\n{status_line}",
            parse_mode="HTML",
            reply_markup=run_project(),
        )
    except Exception as exc:
        await update.callback_query.message.reply_text(
            f"❌ Run failed: {html_mod.escape(str(exc)[:300])}",
            parse_mode="HTML",
            reply_markup=run_project(),
        )


# ── Helpers ───────────────────────────────────────────────────────────────────

def _normalize_interpreter_name(value: str) -> str | None:
    normalized = value.strip().lower().removesuffix(".exe")
    if normalized in _ALLOWED_RUN_INTERPRETERS:
        return normalized
    return None


def _is_safe_relative_path(path: str) -> bool:
    if not isinstance(path, str):
        return False
    cleaned = _normalize_slashes(path.strip())
    if not cleaned:
        return False
    if cleaned.startswith("/") or cleaned.startswith("\\"):
        return False
    if re.match(r"^[A-Za-z]:[\\/]", cleaned):
        return False
    if any(part == ".." for part in cleaned.split("/")):
        return False
    if any(ch in cleaned for ch in ('"', "'", "\n", "\r", "\t")):
        return False
    return True


def _is_safe_cli_token(token: str) -> bool:
    if not isinstance(token, str):
        return False
    value = token.strip()
    if not value:
        return False
    if any(ch.isspace() for ch in value):
        return False
    if any(ch in value for ch in ('"', "'", "\n", "\r", "\t")):
        return False
    return True


def _build_run_command(
    *,
    interpreter: str,
    entrypoint: str,
    args: list[str] | None = None,
) -> tuple[str, str] | None:
    args = args or []
    normalized_interpreter = _normalize_interpreter_name(interpreter)
    if not normalized_interpreter:
        return None
    if not _is_safe_relative_path(entrypoint):
        return None
    if any(not _is_safe_cli_token(arg) for arg in args):
        return None

    normalized_target = _normalize_slashes(entrypoint.strip()).lstrip("./")
    if not normalized_target:
        return None
    command_parts = [normalized_interpreter, normalized_target, *args]
    return " ".join(command_parts), normalized_target


def _resolve_run_manifest(manifest_text: str) -> tuple[str, str] | None:
    """
    Resolve command tuple from skynet_run.json content.
    """
    try:
        payload = json.loads(manifest_text)
    except Exception:
        return None

    if not isinstance(payload, dict):
        return None

    # Backward-compatible path: allow explicit command while still validating.
    command_value = payload.get("command")
    if isinstance(command_value, str) and command_value.strip():
        tokens = command_value.strip().split()
        if len(tokens) < 2:
            return None
        interpreter = tokens[0]
        entrypoint = tokens[1]
        args = tokens[2:]
        return _build_run_command(
            interpreter=interpreter,
            entrypoint=entrypoint,
            args=args,
        )

    interpreter = payload.get("interpreter")
    entrypoint = payload.get("entrypoint")
    args_value = payload.get("args", [])
    if not isinstance(interpreter, str) or not isinstance(entrypoint, str):
        return None

    if args_value is None:
        args: list[str] = []
    elif isinstance(args_value, list) and all(isinstance(item, str) for item in args_value):
        args = [item.strip() for item in args_value if item.strip()]
    else:
        return None

    return _build_run_command(
        interpreter=interpreter,
        entrypoint=entrypoint,
        args=args,
    )


def _find_run_manifest(files: list[str]) -> str | None:
    preferred_name = _RUN_MANIFEST_FILENAME.lower()
    for candidate in files:
        if candidate.lower() == preferred_name:
            return candidate
    for candidate in files:
        if candidate.lower().endswith("/" + preferred_name):
            return candidate
    return None


def _project_prefers_node(project_type: str) -> bool:
    lowered = project_type.lower()
    return any(token in lowered for token in ("javascript", "node", "react", "next.js", "js"))


def _normalize_slashes(path: str) -> str:
    return path.replace("\\", "/")


def _to_relative_path(path: str, *, working_dir: str) -> str:
    """
    Best-effort conversion of discovered paths to a path runnable from working_dir.
    """
    norm_path = _normalize_slashes(path).strip()
    norm_working_dir = _normalize_slashes(working_dir).rstrip("/")
    if not norm_path:
        return norm_path
    if norm_working_dir and norm_path.lower().startswith((norm_working_dir + "/").lower()):
        return norm_path[len(norm_working_dir) + 1 :]
    return norm_path


def _extract_file_paths_from_listing(listing: str, *, working_dir: str) -> list[str]:
    """
    Parse list_directory output (including recursive [DIR] format) into file paths.
    """
    files: list[str] = []
    dir_stack: list[str] = []

    for raw_line in listing.splitlines():
        line = raw_line.rstrip()
        if not line or line == "... (truncated)":
            continue

        stripped = line.lstrip(" ")
        indent = len(line) - len(stripped)
        depth = max(0, indent // 2)

        if stripped.startswith("[DIR] "):
            dir_name = stripped[len("[DIR] ") :].strip().rstrip("/\\")
            if not dir_name:
                continue

            # Absolute fallback formats may include a full path in [DIR] lines.
            if re.match(r"^[A-Za-z]:[\\/]", dir_name) or dir_name.startswith("/"):
                rel_dir = _to_relative_path(dir_name, working_dir=working_dir).strip("/")
                dir_stack = [p for p in _normalize_slashes(rel_dir).split("/") if p]
                continue

            if depth <= len(dir_stack):
                dir_stack = dir_stack[:depth]
            dir_stack.append(dir_name)
            continue

        file_name = re.sub(r"\s+\(\d+\s+bytes\)\s*$", "", stripped).strip()
        if not file_name:
            continue

        if re.match(r"^[A-Za-z]:[\\/]", file_name) or file_name.startswith("/"):
            rel_file = _to_relative_path(file_name, working_dir=working_dir)
        else:
            prefix = "/".join(dir_stack[:depth]) if depth <= len(dir_stack) else "/".join(dir_stack)
            rel_file = f"{prefix}/{file_name}" if prefix else file_name
        rel_file = _normalize_slashes(rel_file).lstrip("./")
        if rel_file:
            files.append(rel_file)

    # Preserve order while removing duplicates (case-insensitive for Windows paths).
    unique_files: list[str] = []
    seen: set[str] = set()
    for filepath in files:
        key = filepath.lower()
        if key in seen:
            continue
        seen.add(key)
        unique_files.append(filepath)
    return unique_files


def _select_entrypoint(
    *,
    files: list[str],
    slug: str,
    project_type: str,
) -> tuple[str, str] | None:
    """
    Return (command, target_path) for the best .py/.js entrypoint candidate.
    """
    slug_lower = slug.lower()
    type_prefers_node = _project_prefers_node(project_type)
    candidates: list[tuple[int, str, str]] = []  # (score, interpreter, path)

    for path in files:
        norm_path = _normalize_slashes(path).strip()
        lower = norm_path.lower()
        if lower.endswith(".py"):
            interpreter = "python"
        elif lower.endswith(".js"):
            interpreter = "node"
        else:
            continue

        basename = lower.rsplit("/", 1)[-1]
        depth = lower.count("/")
        score = 0

        if basename in (f"{slug_lower}.py", f"{slug_lower}.js"):
            score += 120
        if basename in ("main.py", "app.py", "index.py", "main.js", "app.js", "index.js", "server.js"):
            score += 90

        if depth == 0:
            score += 20
        score -= depth * 2

        if " " in norm_path:
            score -= 10

        if type_prefers_node and interpreter == "node":
            score += 40
        if not type_prefers_node and interpreter == "python":
            score += 15

        candidates.append((score, interpreter, norm_path))

    if not candidates:
        return None

    candidates.sort(key=lambda item: (-item[0], item[2].lower()))
    _, interpreter, target = candidates[0]
    return f"{interpreter} {target}", target


async def _extract_milestones(router, project: dict) -> list[str]:
    """
    Ask the LLM to extract an ordered list of coding milestones from the plan.
    Returns a list of milestone description strings.
    """
    plan = project.get("description", "")
    if not plan:
        return []

    system = (
        "You are a project planner. Extract the coding milestones from the project plan "
        "as a JSON array of strings. Each element is ONE self-contained coding task "
        "(e.g. 'Set up project structure', 'Implement login endpoint'). "
        "Output ONLY a valid JSON array, no extra text."
    )
    messages = [
        {
            "role": "user",
            "content": f"Project: {project['name']}\n\nPlan:\n{plan}\n\n"
                       "Return the milestones as a JSON array of strings.",
        }
    ]

    try:
        response = await router.chat(
            messages=messages,
            system=system,
            max_tokens=1024,
            task_type="planning",
        )
        raw = (response.text or "").strip()
        # Strip markdown code fences if present.
        raw = re.sub(r"^```(?:json)?\s*", "", raw)
        raw = re.sub(r"\s*```$", "", raw)
        milestones = json.loads(raw)
        if isinstance(milestones, list) and all(isinstance(m, str) for m in milestones):
            return [m.strip() for m in milestones if m.strip()]
    except Exception:
        logger.warning("JSON milestone extraction failed — falling back to line parsing")

    # Fallback: split on numbered list items (1. ... 2. ...)
    fallback = _parse_milestones_fallback(plan)
    if fallback:
        return fallback

    # Last resort: ask the LLM to generate milestones from the project name and type
    # (handles cases where the plan text is garbage or a meta-response).
    logger.warning("No milestones found in plan text — generating from project info")
    try:
        gen_system = (
            "You are a project planner. Generate 2-4 coding milestones for the given project. "
            "Each milestone is ONE self-contained coding task. "
            "Output ONLY a valid JSON array of strings, no extra text."
        )
        gen_messages = [{
            "role": "user",
            "content": (
                f"Project name: {project['name']}\n"
                f"Type: {project.get('project_type', 'Other')}\n"
                f"Description: {plan[:500]}\n\n"
                "Generate milestones as a JSON array of strings."
            ),
        }]
        response = await router.chat(
            messages=gen_messages, system=gen_system,
            max_tokens=512, task_type="planning",
        )
        raw = (response.text or "").strip()
        raw = re.sub(r"^```(?:json)?\s*", "", raw)
        raw = re.sub(r"\s*```$", "", raw)
        milestones = json.loads(raw)
        if isinstance(milestones, list) and all(isinstance(m, str) for m in milestones):
            return [m.strip() for m in milestones if m.strip()]
    except Exception:
        logger.warning("Last-resort milestone generation also failed")

    return []


def _parse_milestones_fallback(plan: str) -> list[str]:
    """Extract numbered list items from free-form plan text."""
    pattern = re.compile(r"^\s*\d+\.\s+(.+)", re.MULTILINE)
    matches = pattern.findall(plan)
    return [m.strip() for m in matches if m.strip()]


def _slugify(name: str) -> str:
    """Convert a project name to a safe directory/repo slug."""
    slug = re.sub(r"[^a-z0-9-]", "", name.lower().replace(" ", "-"))
    slug = re.sub(r"-+", "-", slug).strip("-")
    return slug or "project"
