"""
SKYNET Gateway — Configuration

Runs on your EC2 instance.  Accepts inbound WebSocket connections
from CHATHAN workers and provides an HTTP API + Telegram interface.

SECURITY: Load AUTH_TOKEN from environment in production.
"""

import os


def _str_env(*names: str, default: str) -> str:
    """
    Str env.
    
    Purpose:
    - Implement `_str_env` within this module's workflow.
    - Keep behavior localized so callers have one stable entrypoint.
    
    How it works:
    - Consumes declared inputs, performs local validation/transforms, and applies the function logic.
    - Produces deterministic return data or side effects expected by calling code.
    
    Why this exists:
    - Prevents duplicated logic in upstream orchestration paths.
    - Improves debuggability by centralizing this behavior in one named function.
    
    Parameters:
    - `*names`: input used by this function to compute or route work.
    - `default`: input used by this function to compute or route work.
    
    Returns:
    - Return value typed as `str` when available; otherwise side effects only.
    """

    for name in names:
        value = os.environ.get(name)
        if value is not None and value.strip():
            return value.strip()
    return default


def _int_env(*names: str, default: int) -> int:
    """
    Int env.
    
    Purpose:
    - Implement `_int_env` within this module's workflow.
    - Keep behavior localized so callers have one stable entrypoint.
    
    How it works:
    - Consumes declared inputs, performs local validation/transforms, and applies the function logic.
    - Produces deterministic return data or side effects expected by calling code.
    
    Why this exists:
    - Prevents duplicated logic in upstream orchestration paths.
    - Improves debuggability by centralizing this behavior in one named function.
    
    Parameters:
    - `*names`: input used by this function to compute or route work.
    - `default`: input used by this function to compute or route work.
    
    Returns:
    - Return value typed as `int` when available; otherwise side effects only.
    """

    for name in names:
        raw = os.environ.get(name)
        if raw is None or not raw.strip():
            continue
        try:
            return int(raw)
        except ValueError:
            continue
    return default


def _bool_env(*names: str, default: bool) -> bool:
    """
    Bool env.
    
    Purpose:
    - Implement `_bool_env` within this module's workflow.
    - Keep behavior localized so callers have one stable entrypoint.
    
    How it works:
    - Consumes declared inputs, performs local validation/transforms, and applies the function logic.
    - Produces deterministic return data or side effects expected by calling code.
    
    Why this exists:
    - Prevents duplicated logic in upstream orchestration paths.
    - Improves debuggability by centralizing this behavior in one named function.
    
    Parameters:
    - `*names`: input used by this function to compute or route work.
    - `default`: input used by this function to compute or route work.
    
    Returns:
    - Return value typed as `bool` when available; otherwise side effects only.
    """

    for name in names:
        raw = os.environ.get(name)
        if raw is None or not raw.strip():
            continue
        return raw.strip().lower() in {"1", "true", "yes", "on"}
    return default


# ---------------------------------------------------------------------------
# Network
# ---------------------------------------------------------------------------
WS_HOST: str = _str_env("OPENCLAW_WS_HOST", "SKYNET_WS_HOST", default="0.0.0.0")
WS_PORT: int = _int_env("OPENCLAW_WS_PORT", "SKYNET_WS_PORT", default=8765)

# Keep loopback default for secure single-process setups; set OPENCLAW_HTTP_HOST=0.0.0.0
# when SKYNET must access this API over a container/network boundary.
HTTP_HOST: str = _str_env("OPENCLAW_HTTP_HOST", "SKYNET_HTTP_HOST", default="127.0.0.1")
HTTP_PORT: int = _int_env("OPENCLAW_HTTP_PORT", "SKYNET_HTTP_PORT", default=8766)

# ---------------------------------------------------------------------------
# TLS — paths to cert/key generated by setup_tls.sh
# ---------------------------------------------------------------------------
TLS_CERT: str = os.environ.get(
    "SKYNET_TLS_CERT",
    os.environ.get(
        "OPENCLAW_TLS_CERT",
        os.path.join(os.path.dirname(__file__), "certs", "server.crt"),
    ),
)
TLS_KEY: str = os.environ.get(
    "SKYNET_TLS_KEY",
    os.environ.get(
        "OPENCLAW_TLS_KEY",
        os.path.join(os.path.dirname(__file__), "certs", "server.key"),
    ),
)

# ---------------------------------------------------------------------------
# Authentication — must match the token configured on the CHATHAN worker
# ---------------------------------------------------------------------------
AUTH_TOKEN: str = os.environ.get(
    "SKYNET_AUTH_TOKEN", os.environ.get("OPENCLAW_AUTH_TOKEN", ""),
)

# ---------------------------------------------------------------------------
# Timeouts
# ---------------------------------------------------------------------------
# How long to wait for a CHATHAN worker response before timing out (seconds).
ACTION_TIMEOUT_SECONDS: int = 120

# WebSocket keep-alive.
WS_PING_INTERVAL: int = 30
WS_PING_TIMEOUT: int = 10

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
LOG_LEVEL: str = os.environ.get(
    "SKYNET_LOG_LEVEL", os.environ.get("OPENCLAW_LOG_LEVEL", "INFO"),
)

LOG_DIR: str = _str_env(
    "SKYNET_LOG_DIR",
    "OPENCLAW_LOG_DIR",
    default=os.path.join(os.path.dirname(__file__), "logs"),
)

TRACE_MIRROR_LOG_DIR: str = _str_env(
    "SKYNET_TRACE_MIRROR_LOG_DIR",
    "OPENCLAW_TRACE_MIRROR_LOG_DIR",
    default=r"E:\SKYNET-SANDBOX\logs",
)

LOG_MAX_BYTES: int = _int_env(
    "SKYNET_LOG_MAX_BYTES",
    "OPENCLAW_LOG_MAX_BYTES",
    default=25 * 1024 * 1024,
)

LOG_BACKUP_COUNT: int = _int_env(
    "SKYNET_LOG_BACKUP_COUNT",
    "OPENCLAW_LOG_BACKUP_COUNT",
    default=10,
)

LOG_ENABLE_LOCAL_FILES: bool = _bool_env(
    "SKYNET_LOG_ENABLE_LOCAL_FILES",
    "OPENCLAW_LOG_ENABLE_LOCAL_FILES",
    default=True,
)

LOG_ENABLE_SSH_MIRROR: bool = _bool_env(
    "SKYNET_LOG_ENABLE_SSH_MIRROR",
    "OPENCLAW_LOG_ENABLE_SSH_MIRROR",
    default=False,
)

LOG_SSH_HOST: str = _str_env("OPENCLAW_SSH_HOST", default="127.0.0.1")
LOG_SSH_PORT: int = _int_env("OPENCLAW_SSH_PORT", default=2222)
LOG_SSH_USER: str = _str_env("OPENCLAW_SSH_USER", default="")
LOG_SSH_KEY_PATH: str = _str_env("OPENCLAW_SSH_KEY_PATH", default="")
LOG_SSH_PASSWORD: str = os.environ.get("OPENCLAW_SSH_PASSWORD", "")
LOG_SSH_STRICT_HOST_KEY: bool = _bool_env("OPENCLAW_SSH_STRICT_HOST_KEY", default=False)
LOG_SSH_CONNECT_TIMEOUT: int = _int_env("OPENCLAW_SSH_CONNECT_TIMEOUT", default=4)
LOG_SSH_COMMAND_TIMEOUT: int = _int_env("OPENCLAW_SSH_COMMAND_TIMEOUT", default=180)

LOG_S3_ENABLED: bool = _bool_env(
    "SKYNET_LOG_S3_ENABLED",
    "OPENCLAW_LOG_S3_ENABLED",
    default=False,
)
LOG_S3_BUCKET: str = _str_env("SKYNET_S3_BUCKET", "OPENCLAW_S3_BUCKET", default="")
LOG_S3_REGION: str = _str_env("AWS_REGION", "AWS_DEFAULT_REGION", default="us-east-1")
LOG_S3_PREFIX: str = _str_env(
    "SKYNET_LOG_S3_PREFIX",
    "OPENCLAW_LOG_S3_PREFIX",
    default="openclaw/logs",
)
