"""
SKYNET Gateway — Configuration

Runs on your EC2 instance.  Accepts inbound WebSocket connections
from CHATHAN workers and provides an HTTP API + Telegram interface.

SECURITY: Load AUTH_TOKEN from environment in production.
"""

import os

# ---------------------------------------------------------------------------
# Network
# ---------------------------------------------------------------------------
WS_HOST: str = "0.0.0.0"
WS_PORT: int = 8765

HTTP_HOST: str = "127.0.0.1"   # HTTP API listens on loopback only
HTTP_PORT: int = 8766

# ---------------------------------------------------------------------------
# TLS — paths to cert/key generated by setup_tls.sh
# ---------------------------------------------------------------------------
TLS_CERT: str = os.environ.get(
    "SKYNET_TLS_CERT",
    os.environ.get(
        "OPENCLAW_TLS_CERT",
        os.path.join(os.path.dirname(__file__), "certs", "server.crt"),
    ),
)
TLS_KEY: str = os.environ.get(
    "SKYNET_TLS_KEY",
    os.environ.get(
        "OPENCLAW_TLS_KEY",
        os.path.join(os.path.dirname(__file__), "certs", "server.key"),
    ),
)

# ---------------------------------------------------------------------------
# Authentication — must match the token configured on the CHATHAN worker
# ---------------------------------------------------------------------------
AUTH_TOKEN: str = os.environ.get(
    "SKYNET_AUTH_TOKEN", os.environ.get("OPENCLAW_AUTH_TOKEN", ""),
)

# ---------------------------------------------------------------------------
# Timeouts
# ---------------------------------------------------------------------------
# How long to wait for a CHATHAN worker response before timing out (seconds).
ACTION_TIMEOUT_SECONDS: int = 120

# WebSocket keep-alive.
WS_PING_INTERVAL: int = 30
WS_PING_TIMEOUT: int = 10

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
LOG_LEVEL: str = os.environ.get(
    "SKYNET_LOG_LEVEL", os.environ.get("OPENCLAW_LOG_LEVEL", "INFO"),
)
